### ISSUE TITLE
The full dimension not loading properly in creative mode with almost all known dimension mods for 1.16.5 installed. Only the dream dimensions work, and not using Optifine. Mod version: Latest for 1.16.5, 2.2.3-4

### ISSUE THREAD

**Issue by SetaCraft** [Y3Z0N/theabyss#98] opened 2023-06-05 02:21 UTC
### Describe the Bug

I downloaded almost every single dimension mod for 1.16.5 to see what happens, and when I try to go into the full dimension after following the steps in creative mode, it loads, but the blocks and mobs are invisible, and the map doesn't load in general. I am not using Optifine because of Twilight Forest, and not Rubidium because some mods are not compatible with it (because I want to make a modpack of 200-300+ mods for a server in the future if I get a very powerful PC).

The version of the mod I am using is the latest for 1.16.5, 2.2.3-4.
![2023-06-05_03 51 07](https://github.com/Y3Z0N/theabyss/assets/130748044/38d55372-0349-4e4c-b8bf-c37ff45b4b8e)

### Reproduction Steps

1. Download the mods I used here: https://drive.google.com/file/d/1l38pH4GHYQ6dYb5DE5BCKAQRgTaJmyuo/view?usp=sharing
2. Use Forge for 1.16.5.
3. Follow the steps to enter the Abyss, then create the portal.
4. Enter the portal and see if it happens the same thing as me.

### Expected Result

The full dimension not loading properly.

### Operating System

Windows 11

### Mod Version

2.2.2

### Minecraft Version

1.19.2

### Forge Version

36.2.39

### Additional Context

Not using Optifine.

**Comment by IKarum** [comment] 2023-08-09 20:24
Im with the same problem

**Comment by Y3Z0N** [comment] 2024-04-01 03:45
Caused by PlayerEX mod disable its GUI or remove their mod. anyways it is fixed on my side on 1.20.1

**Closed as completed by Y3Z0N** 2024-04-01 03:45 UTC
Labels: bug
